Repository solguruz/multi_selection_filter, pull requests merged in 2023-10, with the labels that each got.

#11 [Feature] Making example code simple
  example/lib/constants/app_constants.dart
  example/lib/helper/helper.dart
  example/lib/main.dart
  example/lib/models/food_item_model.dart
Labels: enhancement

#16 [Feature] Adding more dart documentation comments
  lib/src/presentation/common/common_widgets.dart
  lib/src/presentation/multi_selection_filter.dart
  lib/src/utils/size_util.dart
Labels: documentation

#17 [Refactor] Removing unnecessary parameter
  README.md
  example/lib/main.dart
  lib/src/constants/constants.dart
  lib/src/presentation/multi_selection_filter.dart
Labels: Refactor

#19 [Refactor] Code separation
  lib/src/presentation/multi_selection_filter.dart
Labels: Refactor

#18 [Feature] Updating README file
  .github/behance.svg
  .github/dribbble.svg
  .github/explore_our_flutter_service.svg
  .github/facebook.svg
  .github/hire_flutter_developer.svg
  .github/instagram.svg
  .github/linkedin.svg
  .github/multi_select_filter_1.png
  .github/multi_select_filter_2.png
  .github/select_multi_filter_main.png
  .github/solguruz.svg
  .github/twitter.svg
  README.md
Labels: documentation, enhancement, good first issue
